### ISSUE TITLE
About Theme Colors 📦

### ISSUE THREAD

**Issue by pl1998** [enzostvs/vue3-discordpicker#2]
Thank you for writing 🙏 🙏🙏  this plugin to provide theme colors 🚗 🚕 🚙  🚌

**Comment by enzostvs** [comment]
Hi @pl1998 
Would you like to have the possibility to change the theme?
Can you provide me with a list of themes? :-) thanks

**Comment by enzostvs** [comment]
Hi @pl1998 , some news ?
If no news tomorrow i close this issue
Thanks
