### ISSUE TITLE
Can you add the image uploading icon and the method

### ISSUE THREAD

**Issue by pl1998** [enzostvs/vue3-discordpicker#4]
Can you add the image uploading icon and the method

**Comment by pl1998** [comment]
Thank you very much 🙏。😘

**Comment by enzostvs** [comment]
> Thank you very much 🙏。😘

Hi i dont understand, do you have an example ?

**Comment by pl1998** [comment]
Now I am making a chat tool and using your plug-in, I need to add an icon and provide a method of picture uploading. May I ask if you have time to add the plug-in
![image](https://user-images.githubusercontent.com/43993206/125571919-0fec191e-4fd0-420b-aeff-f41062de79a3.png)
![image](https://user-images.githubusercontent.com/43993206/125571976-6794e305-57e1-46aa-91f0-fc3ea770d0af.png)

**Comment by enzostvs** [comment]
Oh okay, i think it well be okay next week.
You want just a click emit on icon, or a method to upload and return file ?

**Comment by pl1998** [comment]
Yes, Thank you very much ～🙏

**Comment by pl1998** [comment]
Ha ha ha, brother, are you free 😂 😂 😂

**Comment by enzostvs** [comment]
Hi, sorry I'm currently out of town

**Comment by pl1998** [comment]
haha~ Wish you a nice holiday

**Comment by pl1998** [comment]
Hi, SORRY to bother you. When are you free?

**Comment by pl1998** [comment]
https://user-images.githubusercontent.com/43993206/128497466-448db991-88a7-4285-8023-04669b23bd42.mp4

Make a chat app chat box using your package

**Comment by enzostvs** [comment]
Hi, sorry in France we are in the middle of summer, so I'm quite busy now
What I can try to do quickly is to simply add the possibility to add slots that will go on the side, what do you think?

**Comment by pl1998** [comment]
Thank you very much. I just need the component to provide the method entry and I can take care of the rest

**Comment by enzostvs** [comment]
Hi @pl1998 
I just added 2 things:
An icon on the left as discord with an event click for your upload.
And also the possibility to pass a slot that will go on the right with the gif/emoji icons if you ever want to add other actions.

Let me know if it's ok for you.

**Comment by pl1998** [comment]
Thank you very much!!!🍻
