### ISSUE TITLE
[ Suggestion ] Allow to remove GIF/Emojis & Data sources

### ISSUE THREAD

**Issue by nikuscs** [enzostvs/vue3-discordpicker#5]
Hey, first off thanks for the amazing package, i would ove to suggest some changes and if i have time i might be able to push a PR. Just wanna keep here for reference:

- Ability to pass a prop to disable GIFs and go on "emoji mode" only
- Ability to Pass a prop to disable Emojis and only use Gifs.
- Ability to Toggle Multiple Emojis at once and let us control when it opens/close
- Ability to provide a data source to Load the SVG / Icons from another source rather then from your site 'https://en-zo.dev..' privacy and security concerns 📦 

Once again thanks for the lovly design and component :D

**Comment by enzostvs** [comment]
Hello @igerslike ,
I have just added an option "sources" (object) where you can pass custom urls in the desired keys.
If you want for example to change the search icon:

options = { search: 'myurl.png' }

I also added the multiple property to not close the emoji picker at each click
